openapi: 3.0.2
info:
  version: '1.0'
  title: Server Override
  description: For testing operation server override. Possible to list servers for specific operation that overrides default list.
servers:
  - url: http://www.defaultserver.com
paths:
  /global-api-server:
    get:
      summary: This path sends request to API servers defined at global level
      responses:
        '200':
          description: Successful operation
  /path-specific-api-server:
    get:
      summary: This path sends request to API servers defined at Path level
      description: '`server variables` at path level is not yet supported by RapiDoc'
      responses:
        '200':
          description: Successful operation
    servers:
      - url: 'http://example.com/api'
        description: Test server
